"""Tests for the firewall auditor (parser units + mocked run paths)."""

from __future__ import annotations

import pytest

from sectoolkit.tools.defense import firewall_audit as fa

IPTABLES_SAMPLE = """# Generated by iptables-save
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-CUSTOM - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j DROP
-A FORWARD -j DROP
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-CUSTOM2 - [0:0]
COMMIT
"""

NFT_SAMPLE = """table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		ip daddr 127.0.0.1 drop
		meta l4proto tcp accept
	}
	chain forward {
		type filter hook forward priority filter; policy drop;
	}
	chain output {
		type filter hook output priority filter; policy accept;
	}
}
"""

TCP_PROC_SAMPLE = """  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000:0050 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 12345 1 0000000000000000 100 0 0 10 0
   1: 00000000:0035 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 12346 1 0000000000000000 100 0 0 10 0
   2: 7F000001:1F90 00000000:0000 01 00000000:00000000 00:00000000 00000000     0        0 12347 1 0000000000000000 100 0 0 10 0
"""


class TestParseIptables:
    def test_chains_policies_and_rules(self):
        tables = fa.parse_iptables_save(IPTABLES_SAMPLE)
        assert "filter" in tables and "nat" in tables
        inp = tables["filter"]["INPUT"]
        assert inp["policy"] == "drop"
        assert inp["rule_count"] == 3
        assert "lo" in inp["rules"][0]

    def test_summary_targets(self):
        summary = {c["chain"]: c for c in fa.summarize_iptables(fa.parse_iptables_save(IPTABLES_SAMPLE))}
        assert summary["INPUT"]["policy"] == "drop"
        assert summary["INPUT"]["targets"]["ACCEPT"] == 2
        assert summary["INPUT"]["targets"]["DROP"] == 1


class TestParseNft:
    def test_policy_and_rules(self):
        chains = fa.parse_nft_ruleset(NFT_SAMPLE)
        by_name = {c["chain"]: c for c in chains}
        assert by_name["input"]["policy"] == "drop"
        assert by_name["output"]["policy"] == "accept"
        assert by_name["input"]["rule_count"] == 1

    def test_empty_string_is_safe(self):
        assert fa.parse_nft_ruleset("") == []


class TestProcNetTcp:
    def test_listen_rows_only(self):
        ports = fa.parse_proc_net_tcp(TCP_PROC_SAMPLE)
        assert [p["port"] for p in ports] == [80, 53]  # 0x50, 0x35 ; 0x1F90 is ESTAB (state 01)
        assert ports[0]["addr"] == "0.0.0.0"
        assert ports[0]["proto"] == "tcp"


class TestRun:
    def test_unprivileged_ruleset_falls_back_to_ports(self, sample_context, monkeypatch):
        monkeypatch.setattr(fa.shutil, "which", lambda name: name == "nft")
        monkeypatch.setattr(fa, "_run_tool", lambda *a, **k: (_ for _ in ()).throw(PermissionError("denied")))
        monkeypatch.setattr(fa, "_listening_ports_linux", lambda: [{"port": 2222, "addr": "0.0.0.0", "service": "", "proto": "tcp"}])
        result = fa.run({"backend": "auto", "timeout": 5, "check_listening": True}, sample_context)
        assert "ruleset_error" in result
        assert result["ruleset_error"] in ("denied", "required command not found: iptables-save")
        assert result["listening_ports"] == [{"port": 2222, "addr": "0.0.0.0", "service": "", "proto": "tcp"}]
        assert any("privileges" in w for w in result["warnings"])

    def test_iptables_run_and_warnings(self, sample_context, monkeypatch):
        monkeypatch.setattr(fa.shutil, "which",
                            lambda name: name in ("iptables", "iptables-save"))
        monkeypatch.setattr(fa, "_run_tool", lambda cmd, timeout: IPTABLES_SAMPLE)
        monkeypatch.setattr(fa, "_listening_ports_linux", lambda: [])
        result = fa.run({"backend": "iptables", "timeout": 5, "check_listening": True}, sample_context)
        assert any(c["chain"] == "INPUT" and c["policy"] == "drop" for c in result["chains"])
        assert not any("INPUT" in w and "ACCEPT" in w for w in result["warnings"])
        assert "listening_ports" in result

    def test_nft_policy_warns_on_accept(self, sample_context, monkeypatch):
        monkeypatch.setattr(fa.shutil, "which", lambda name: name == "nft")
        monkeypatch.setattr(fa, "_run_tool", lambda cmd, timeout: NFT_SAMPLE)
        monkeypatch.setattr(fa, "_listening_ports_linux", lambda: [])
        result = fa.run({"backend": "auto", "timeout": 5, "check_listening": False}, sample_context)
        assert result["backend"] == "nftables"
        assert any("output" in c["chain"] for c in result["chains"])
        assert not any("ACCEPT" in w for w in result["warnings"])  # only input policy matters, drop here

    def test_common_port_warning(self, sample_context, monkeypatch):
        monkeypatch.setattr(fa.shutil, "which", lambda name: name == "nft")
        monkeypatch.setattr(fa, "_run_tool", lambda cmd, timeout: NFT_SAMPLE)
        monkeypatch.setattr(fa, "_listening_ports_linux",
                            lambda: [{"port": 22, "addr": "0.0.0.0", "service": "ssh", "proto": "tcp"}])
        result = fa.run({"backend": "auto", "timeout": 5, "check_listening": True}, sample_context)
        assert any("22" in w and "ssh" in w for w in result["warnings"])

    def test_missing_command_falls_back_to_ports(self, sample_context, monkeypatch):
        monkeypatch.setattr(fa.shutil, "which", lambda name: None)
        monkeypatch.setattr(fa, "_listening_ports_linux", lambda: [])
        result = fa.run({"backend": "iptables", "timeout": 5, "check_listening": True}, sample_context)
        assert "ruleset_error" in result
        assert "not found" in result["ruleset_error"]
        assert "listening_ports" in result

    def test_render_readable(self):
        text = fa.render({
            "backend": "iptables",
            "chains": [{"table": "filter", "chain": "INPUT", "policy": "drop", "rule_count": 2}],
            "listening_ports": [{"proto": "tcp", "port": 22, "service": "ssh", "addr": "0.0.0.0"}],
            "warnings": ["! INPUT policy ACCEPT"],
        })
        assert "INPUT" in text and "ssh" in text and "ACCEPT" in text