"""Custom Metasploit Module generator — W7 Red Team / C2.

Generates a starter Metasploit Ruby module skeleton for learning how to
structure modules (references, check() vs exploit(), payload composition) —
it does NOT run Metasploit and does not touch any host.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

from ...core.tool import FieldSpec, ToolContext, ToolMeta

TOOL = ToolMeta(
    name="metasploit-module",
    title="Custom Metasploit Module Generator",
    wave=7,
    description=(
        "Produce a starter Metasploit Ruby module (auxiliary/exploit/post) "
        "for your authorized targets. Writes local .rb only; never "
        "runs the framework and never connects to any host by itself."
    ),
    category="redteam",
    mode="read",
    privileges="none",
    destructive=False,
    fields=[
        FieldSpec(name="module_name", label="Module name (e.g. lab_bofrc)",
                  type="text", default="lab_echo_aux"),
        FieldSpec(name="module_type", label="Module type", type="combo",
                  options=["auxiliary", "exploit", "post"], default="auxiliary"),
        FieldSpec(name="description", label="Module description", type="text",
                  default="Lab service enumeration module for authorized "
                          "testing."),
        FieldSpec(name="default_port", label="Default port", type="int",
                  default=4444),
        FieldSpec(name="output_file", label="Output .rb file", type="file",
                  default=None),
    ],
)


def _sanitize(name: str) -> str:
    import re
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not name or not name[0].isalpha():
        name = "msf_" + name
    return name


def _render_auxiliary(name: str, desc: str, port: int) -> str:
    return f"""##
# Starter module skeleton generated by SecurityToolkitSuite.
# For use against systems you own or hold written authorization to test.
##
class MetasploitModule < Msf::Auxiliary
  include Msf::Exploit::Remote::Tcp

  def initialize(info = {{}})
    super(update_info(info,
      'Name'           => '{name}',
      'Description'    => %q({{ {desc} }}),
      'Author'         => ['your-tag'],
      'License'        => MSF_LICENSE,
      'References'     => [ ['URL', 'https://example.com/docs'] ]
    ))
    register_options([
      Opt::RPORT({port})
    ])
  end

  def check
    connect
    banner = sock.get_once
    disconnect
    return Exploit::CheckCode::Appears if banner && !banner.empty?
    Exploit::CheckCode::Unknown
  end

  def run
    check
    connect
    vprint_status("Sending probe")
    sock.put("PROBE\\r\\n")
    data = sock.get_once(-1, 5)
    print_good("Response: {{ data.inspect }}")
    disconnect
  end
end
"""


def _render_exploit(name: str, desc: str, port: int) -> str:
    return f"""##
# Starter exploit skeleton generated by SecurityToolkitSuite.
# For use against systems you own or hold written authorization to test.
##
class MetasploitModule < Msf::Exploit::Remote
  Rank = NormalRanking
  include Msf::Exploit::Remote::Tcp

  def initialize(info = {{}})
    super(update_info(info,
      'Name'        => '{name}',
      'Description' => %q({{ {desc} }}),
      'Author'      => ['your-tag'],
      'License'     => MSF_LICENSE,
      'Platform'    => 'linux',
      'Arch'        => ARCH_X86,
      'References'  => [ ['URL', 'https://example.com/docs'] ]
    ))
    register_options([
      Opt::RPORT({port})
    ])
  end

  def check
    connect
    banner = sock.get_once
    disconnect
    banner ? Exploit::CheckCode::Appears : Exploit::CheckCode::Unknown
  end

  def exploit
    check
    payload = payload.encoded
    connect
    sock.put(payload)
    handler
    disconnect
  end
end
"""


def _render_post(name: str, desc: str) -> str:
    return f"""##
# Starter post-module skeleton (session-based) generated by SecurityToolkitSuite.
# For use on sessions you hold authorization to test.
##
class MetasploitModule < Msf::Post
  include Msf::Post::File
  include Msf::Post::Common

  def initialize(info = {{}})
    super(update_info(info,
      'Name'        => '{name}',
      'Description' => %q({{ {desc} }}),
      'Author'      => ['your-tag'],
      'License'     => MSF_LICENSE
    ))
  end

  def run
    print_status("Running on session \\#\\#{{session.id}}")
    print_good("uname: {{ cmd_exec('uname -a') }}")
  end
end
"""


def run(params: dict, ctx: ToolContext) -> dict:
    name = _sanitize(str(params.get("module_name") or "lab_echo_aux"))
    mtype = str(params.get("module_type") or "auxiliary")
    if mtype not in ("auxiliary", "exploit", "post"):
        raise ValueError("module_type must be auxiliary, exploit, or post")
    desc = str(params.get("description") or
               "Lab service enumeration module for authorized testing.")
    try:
        port = int(params.get("default_port") or 4444)
    except (TypeError, ValueError):
        raise ValueError("default_port must be an integer")

    if mtype == "auxiliary":
        text = _render_auxiliary(name, desc, port)
    elif mtype == "exploit":
        text = _render_exploit(name, desc, port)
    else:
        text = _render_post(name, desc)
        port = None

    written = ""
    out = params.get("output_file")
    if out:
        target = Path(str(out))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        written = str(target)
    return {"module_name": name, "module_type": mtype,
            "default_port": port, "ruby_code": text, "output_file": written}


def render(result: dict) -> str:
    lines = [f"Metasploit {result['module_type']} module {result['module_name']}"]
    lines += result["ruby_code"].splitlines()
    if result.get("output_file"):
        lines.append(f"Written to {result['output_file']}")
    return "\n".join(lines)