"""Persistence Mechanism Catalog + Detection Rules — W7 Red Team / C2.

Take a persistence catalogue (from the W6 ``persistence-catalog`` JSON output,
or scan a directory tree directly) and generate Sigma-style detection rules
(YAML) plus a human-readable matrix for the suspicious persistence
mechanisms found. Read-only against catalogs/trees.
"""

from __future__ import annotations

import datetime as _dt
import json
from collections import Counter
from pathlib import Path
from typing import Dict, List

from ...core.tool import FieldSpec, ToolContext, ToolMeta

TOOL = ToolMeta(
    name="persistence-rules",
    title="Persistence Catalog + Detection Rules",
    wave=7,
    description=(
        "Turn a persistence catalog (JSON) — or a live directory scan — into "
        "Sigma-style YAML detection rules and a mechanism matrix. Read-only."
    ),
    category="redteam",
    mode="read",
    privileges="none",
    fields=[
        FieldSpec(name="catalog_json", label="Catalog JSON (from persistence-catalog)",
                  type="file", default=None),
        FieldSpec(name="root", label="Root to scan (if no catalog)",
                  type="dir", default=None),
        FieldSpec(name="output_dir", label="Output rules directory", type="dir",
                  default=None),
    ],
)


def _load_findings(params: dict, ctx: ToolContext) -> list:
    catalog = params.get("catalog_json")
    if catalog:
        path = Path(str(catalog))
        if not path.exists():
            raise ValueError(f"catalog_json not found: {path}")
        data = json.loads(path.read_text(encoding="utf-8"))
        return list(data.get("findings", []))
    root = params.get("root")
    if not root:
        raise ValueError("either catalog_json or root is required")
    from ...tools.malware import persistence_catalog as pc
    res = pc.run({"root": str(root), "max_entries": 500}, ctx)
    return list(res["findings"])


def _sigma_yaml(num: int, title: str, kind: str, path: str, detail: str) -> str:
    def esc(s: str) -> str:
        return (s.replace("\\", "\\\\").replace('"', '\\"')
                .replace("\n", "\\n"))
    field = "Path" if kind in ("systemd-unit", "init-script", "autostart",
                               "cron") else "Details"
    selection = {f"sel_path": f'endswith("{esc(kind)}")'}
    cond = "selection.*"
    return (f"title: {title}\n"
            f"id: {num:08X}-{num:04X}-{num:04X}-{num:04X}-{num:12X}\n"
            f"status: experimental\n"
            f"description: Persistence mechanism candidate "
            f"(generated by SecurityToolkitSuite)\n"
            f"logsource:\n  product: linux\n  category: process_creation\n"
            f"detection:\n  selection:\n    {field}: [{esc(path)!r}]\n"
            f"  condition: {cond}\n"
            f"fields:\n  - CommandLine\n"
            f"level: high\n")


def run(params: dict, ctx: ToolContext) -> dict:
    findings = _load_findings(params, ctx)
    if not findings:
        raise ValueError("no findings to analyze")

    by_kind = dict(Counter(f["kind"] for f in findings))
    mechanisms: Dict[str, List[dict]] = {}
    for f in findings:
        mechanisms.setdefault(f["kind"], []).append(f)

    rules: List[dict] = []
    for i, (kind, items) in enumerate(sorted(mechanisms.items())):
        for n, f in enumerate(items):
            title = f"Persist_Generated_{kind.replace('-', '_')}_{n}"
            rules.append({
                "title": title,
                "kind": kind,
                "path": f["path"],
                "detail": f.get("detail", ""),
                "sigma": _sigma_yaml(i * 1000 + n, title, kind,
                                     f["path"], f.get("detail", "")),
            })

    written: List[str] = []
    out_dir = params.get("output_dir")
    if out_dir:
        root = Path(str(out_dir))
        root.mkdir(parents=True, exist_ok=True)
        for r in rules:
            safe = r["title"]
            target = root / f"{safe}.yml"
            target.write_text(r["sigma"], encoding="utf-8")
            written.append(str(target))

    return {
        "findings_count": len(findings),
        "by_kind": by_kind,
        "rules_count": len(rules),
        "rules": rules,
        "written_rules": written,
        "finished_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
    }


def render(result: dict) -> str:
    lines = [f"Persistence detection rules: {result['rules_count']} written "
             f"from {result['findings_count']} catalog findings"]
    for k, n in result.get("by_kind", {}).items():
        lines.append(f"  mechanism {k}: {n}")
    for r in result.get("rules", [])[:6]:
        lines.append(f"  * {r['title']} ({r['kind']}) {r['path']}"
                     + (f" :: {r['detail'][:60]}" if r['detail'] else ""))
    if result.get("written_rules"):
        lines.append("Written:")
        for w in result["written_rules"]:
            lines.append(f"    {w}")
        return "\n".join(lines)
    for r in result.get("rules", [])[:2]:
        lines.append("---")
        lines.append(r["sigma"])
    return "\n".join(lines)